# AI Engine Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-engine
  namespace: jee-smart-ai
spec:
  replicas: 3  # High availability
  selector:
    matchLabels:
      app: ai-engine
  template:
    metadata:
      labels:
        app: ai-engine
    spec:
      containers:
      - name: ai-engine
        image: jee-smart-ai/ai-engine:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8005
        env:
        - name: DATABASE_URL
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(POSTGRES_DB)"
        - name: REDIS_URL
          value: "redis://$(REDIS_HOST):$(REDIS_PORT)"
        - name: POSTGRES_USER
          valueFrom:
            configMapKeyRef:
              name: jee-app-config
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: jee-app-secrets
              key: POSTGRES_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: jee-app-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: jee-app-config
              key: DB_PORT
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: jee-app-config
              key: POSTGRES_DB
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: jee-app-config
              key: REDIS_HOST
        - name: REDIS_PORT
          valueFrom:
            configMapKeyRef:
              name: jee-app-config
              key: REDIS_PORT
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: jee-app-config
              key: ENVIRONMENT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: jee-app-config
              key: LOG_LEVEL
        - name: BKT_MODEL_PATH
          valueFrom:
            configMapKeyRef:
              name: jee-app-config
              key: BKT_MODEL_PATH
        volumeMounts:
        - name: models-volume
          mountPath: /app/models
        - name: logs-volume
          mountPath: /app/logs
        livenessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 60
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8005
          initialDelaySeconds: 10
          periodSeconds: 10
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "3Gi"
            cpu: "1500m"
      volumes:
      - name: models-volume
        emptyDir: {}
      - name: logs-volume
        emptyDir: {}
---
# AI Engine Service
apiVersion: v1
kind: Service
metadata:
  name: ai-engine-service
  namespace: jee-smart-ai
spec:
  selector:
    app: ai-engine
  ports:
  - port: 8005
    targetPort: 8005
  type: ClusterIP